version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ge-coding-task-sam"
s3_bucket = "coding-task-bucket-sam"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
