AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Getemails Coding Task

Resources:
  SAMApiGatewayCodingChallenge:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging

  LambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.8
      CodeUri: src
      Description: Build api for forget password and recover
      MemorySize: 128
      Timeout: 3
      Events:
        ProxyApiRoot:
          Type: Api 
          Properties:
            RestApiId: !Ref SAMApiGatewayCodingChallenge
            Path: /
            Method: ANY
        ResetPasswordPathApi:
          Type: Api 
          Properties:
            RestApiId: !Ref SAMApiGatewayCodingChallenge
            Path: /reset_password/{user_id}/{token}
            Method: GET
        ProxyApiGreedy:
          Type: Api 
          Properties:
            RestApiId: !Ref SAMApiGatewayCodingChallenge
            Path: /{proxy+}
            Method: ANY

