AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Getemails Coding Task

Resources:
  SAMApiGatewayCodingChallenge:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging

  forgetPasswordPython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: forget_password.forgot_password_handler
      Runtime: python3.8
      CodeUri: src/forget_password
      Description: A forget password lambda handler
      MemorySize: 128
      Timeout: 3
      Events:
        ForgetPasswordAPI:
          Type: Api 
          Properties:
            RestApiId: !Ref SAMApiGatewayCodingChallenge
            Path: /forgetpassword
            Method: POST

  ResetPasswordHTML:
    Type: AWS::Serverless::Function
    Properties:
      Handler: reset_password.password_reset_view_handler
      Runtime: python3.8
      CodeUri: src/reset_password
      Description: A reset password html view host
      MemorySize: 128
      Timeout: 3
      Events:
        ForgetPasswordAPI:
          Type: Api 
          Properties:
            RestApiId: !Ref SAMApiGatewayCodingChallenge
            Path: /recoverpassword/{id}/{token}
            Method: GET
